apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apply-manifest-task.yml
  - eventlistener.yml
  - eventlistener-route.yml
  - pipeline.yml
  - update-deployment-task.yml
