apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: java-maven-minimal
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: el-java-maven-minimal
    weight: 100
  wildcardPolicy: None
